name: Go

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

  test:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test
      run: go test -v ./...

  push:
    if: github.event_name != 'pull_request'
    needs:
    - test
    - build
    runs-on: [self-hosted]
    steps:

    - uses: actions/checkout@v2

    - id: sha
      run: echo "::set-output name=sha::$(git describe --always --tags --dirty)"

    - name: Enable Experimental Docker CLI
      run: |
        echo $'{\n  "experimental": true\n}' | sudo tee /etc/docker/daemon.json
        mkdir -p ~/.docker
        echo $'{\n  "experimental": "enabled"\n}' | sudo tee ~/.docker/config.json
        sudo service docker restart
        docker version -f '{{.Client.Experimental}}'
        docker version -f '{{.Server.Experimental}}'
        docker buildx version

    - name: Set up QEMU
      uses: docker/setup-qemu-action@master
      with:
        platforms: all

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      if: github.event_name != 'pull_request'
      run: make manifest

    - name: Build and push latest
      if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
      run: make manifest-latest
